import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { StudyProvider } from "./StudyContext";
import Provider from "./provider";
import SideBar from "./dashboard/_components/SideBar";
import { SidebarProvider } from "./SidebarContext";
import FloatingStudyElements from "./FloatingStudyElemens";
import { headers } from "next/headers";

export const metadata = {
  title: "CramifyAI",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  // Get the current URL path from the header set by middleware
  const headersList = headers();
  const pathname = headersList.get("x-pathname") || "/";

  // List of authentication routes where sidebar should be hidden
  const authRoutes = ["/sign-in", "/sign-up", "/home"];

  // Check if the current path is an auth page
  const isAuthPage = authRoutes.some(route => pathname.startsWith(route));

  return (
    <ClerkProvider>
      <StudyProvider>
        <html lang="en">
          <body className={outfit.className}>
            <FloatingStudyElements />
            <Toaster position="bottom-right" reverseOrder={false} />
            <Provider>
              <SidebarProvider>
                {/* Flex container for sidebar and main content */}
                <div className="relative flex">
                  {/* Conditionally render sidebar */}
                  {!isAuthPage && (
                    <div className="w-30 fixed h-screen top-0 left-0 z-50">
                      <SideBar />
                    </div>
                  )}

                  {/* Adjust main content layout */}
                  <div className={`mt-0 flex-1 p-6 ${!isAuthPage ? "ml-3" : ""}`}>
                    {children}
                  </div>
                </div>
              </SidebarProvider>
            </Provider>
          </body>
        </html>
      </StudyProvider>
    </ClerkProvider>
  );
}