import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Outfit} from 'next/font/google'
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Toaster } from "react-hot-toast";
import { StudyProvider } from "./StudyContext";

export const metadata = {
  title: "CramifyAI",
  description: "Generated by create next app",
};

const outfit = Outfit({subsets:['latin']})

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <StudyProvider>
    <html lang="en">
      <body
        className={outfit.className}
      >
         <Toaster position="bottom-right" reverseOrder={false} />
        <Provider>
            {children}
        </Provider>
        
      </body>
    </html>
    </StudyProvider>
    </ClerkProvider>
  );
}
